export const Eventinfo = [
  {
    date: "12/31",
    name: "New Year Night",
    subtitle: "time flies",
    property: ["fireworks", "nice"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/1",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/2",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/3",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/4",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/5",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/6",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/7",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/8",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/9",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/10",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
  {
    date: "1/11",
    name: "New Year",
    subtitle: "time flies",
    property: ["popular", "happy"],
    description: "New Year Night",
    host: "oscar",
  },
]
